services:
  main:
    build:
      context: ./f365-main-website
      target: dev
    restart: always
    volumes:
      - ./f365-main-website:/var/www/html
    working_dir: /var/www/html
    command: |
      bash -c "composer install --no-interaction --optimize-autoloader && php-fpm"

  nginx:
    image: nginx:1.27.4-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./f365-main-website:/var/www/html
      - ./f365-main-website/nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - main

  api:
    build:
      context: ./f365-api-server
      target: dev
      args:
        - NODE_ENV=dev
    volumes:
      - ./f365-api-server:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: |
      sh -c "npm install --force && npm run dev:watch"

  db:
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER:-app}", "-p${MYSQL_PASSWORD:-!ChangeMe!}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:
